x-kafka-common-main: &kafka-common-main
  image: apache/kafka:4.1.1
  restart: unless-stopped

x-kafka-common-environment: &kafka-common-environment
  KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091'
  KAFKA_PROCESS_ROLES: "broker,controller"
  KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  KAFKA_LISTENERS: "CONTROLLER://:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,HOST:PLAINTEXT,DOCKER:PLAINTEXT"
  KAFKA_INTER_BROKER_LISTENER_NAME: "DOCKER"
  # Singolo nodo
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2

services:
  kafka-1:
    <<: *kafka-common-main
    container_name: kafka_1
    ports:
      - "${KAFKA_1_PORT}:9092"
    environment:
      # Config necessaria per KRaft (Kafka senza ZooKeeper)
      CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_NODE_ID: 1

      # Listener interni (controller + dentro Docker) e verso l'host
      KAFKA_ADVERTISED_LISTENERS: "HOST://localhost:${KAFKA_1_PORT},DOCKER://kafka-1:9093"
      <<: *kafka-common-environment

    networks:
      - kafka-net

  kafka-2:
    image: apache/kafka:4.1.1
    container_name: kafka_2
    ports:
      - "${KAFKA_2_PORT}:9092"
    environment:
      # Config necessaria per KRaft (Kafka senza ZooKeeper)
      CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_NODE_ID: 2

      # Listener interni (controller + dentro Docker) e verso l'host
      KAFKA_ADVERTISED_LISTENERS: "HOST://localhost:${KAFKA_2_PORT},DOCKER://kafka-2:9093"
      <<: *kafka-common-environment

    networks:
      - kafka-net

  kafka-3:
    image: apache/kafka:4.1.1
    container_name: kafka_3
    ports:
      - "${KAFKA_3_PORT}:9092"
    environment:
      # Config necessaria per KRaft (Kafka senza ZooKeeper)
      CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_NODE_ID: 3

      # Listener interni (controller + dentro Docker) e verso l'host
      KAFKA_ADVERTISED_LISTENERS: "HOST://localhost:${KAFKA_3_PORT},DOCKER://kafka-3:9093"
      <<: *kafka-common-environment

    networks:
      - kafka-net

  kafka-ui:
    image: kafbat/kafka-ui:main
    container_name: kafka_ui
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    ports:
      - "8080:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: "local-3-node"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka-1:9093,kafka-2:9093,kafka-3:9093"
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge
